config/routes.rb
RhythmRefuge::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  get "home/index"
  get "query", to: "home#query"
  get "genres", to: "home#list_by_genre"

  devise_for :users
  resources :remixers

  resources :artists

  resources :tracks

  resources :users

  root 'home#index'

  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  mount_uploader :picture, ImageUploader
  has_and_belongs_to_many :tracks

  validates :name, presence: true
  def self.query name
    if name
      find(:all, :conditions => ['name LIKE ?', "%#{name}%"])
    else
      find(:all)
    end
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    if user_signed_in? && current_user.admin?
      @artist = Artist.new
    elsif user_signed_in? && !current_user.admin?
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end

  # GET /artists/1/edit
  def edit
    if user_signed_in? && !current_user.admin?
      redirect_to root_path
    elsif !user_signed_in?
      redirect_to new_user_session_path
    end
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @artist }
      else
        format.html { render action: 'new' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :bio, :picture)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist, :html => {:multipart => true, :class => "form-horizontal form-signup"}) do |f| %>
  <fieldset>
    <legend>Add An Artist</legend>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        This form contains <%= pluralize(@artist.errors.count, "error") %>
      </div>
      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bio, :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :bio, :size => "80x10" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :picture, :class => "control-label" %>
    <div class="controls">
      <%= f.file_field :picture %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Add Artist", :class => "btn btn-primary" %>
  </div>
  <%= link_to 'Back', artists_path %>
  </fieldset>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Listing artists</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= link_to artist.name, artist_path(artist) %></td>
        <td><%= artist.bio %></td>
        <% if user_signed_in? && current_user.admin? %>
        <td><%= link_to 'Edit', edit_artist_path(artist), :class => "btn btn-primary btn-mini" %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-mini" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if user_signed_in? && current_user.admin? %>
<%= link_to 'New Artist', new_artist_path %>
<% end %>

app/views/artists/new.html.erb
<%= render 'form' %>

app/views/artists/show.html.erb
<div class="container">
<div class="row">
  <div class="span4">
    <h3><%= @artist.name.upcase %></h3>
    <%= image_tag(@artist.picture.url) %>
  </div>
  <div class="span4">
    <h3>Bio</h3>
    <%= @artist.bio %>
  </div>
</div>
<div class="row">
  <div class="span12">
    <h3>Tracks by <%= @artist.name %></h3>
    <table class="table table-hover">
      <thead>
        <tr>
        <th>#</th>
        <th>TRACK NAME</th>
        <th>ARTISTS</th>
        <th>GENRE</th>
        <th>LENGTH</th>
        <th>BPM</th>
        <th>KEY</th>
        <th>RELEASE DATE</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% i=0 %>
      <%  @artist.tracks.each do |track| i+=1 %>
      <tr>
        <td><%= i %>.</td>
        <td><%= link_to track.title, track_path(track) %></td>
        <td>
          <% track.artists.each do |artist| %>
          <%= link_to artist.name, artist_path(artist) %>
          <%= ", " unless artist == track.artists.last %>
          <% end %>
        </td>
        <td><%= track.genre %></td>
        <td><%= track.length %></td>
        <td><%= track.bpm %></td>
        <td><%= track.key %></td>
        <td><%= track.release_date %></td>
        <td><%= track.price %></td>
        <td><%= link_to raw("<i class=\"icon-shopping-cart\"></i>"), line_items_path(track_id: track), class: "btn-btn-success", method: :post %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  </div>
</div>
</div>