config/routes.rb
RhythmRefuge::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  get "home/index"
  get "query", to: "home#query"
  get "genres", to: "home#list_by_genre"

  devise_for :users
  resources :remixers

  resources :artists

  resources :tracks

  resources :users

  root 'home#index'

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items

  validates :first_name, :last_name, :cc_type, :cc_number, :exp_month, :exp_year, :addr_1, :city, :zip, :state, :presence => true
  

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      self.line_items << item
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    if current_user.id != @order.user_id
      redirect_to root_url
      return
    end

    @line_items = @order.line_items
  end

  # GET /orders/new
  def new
    @cart = current_user.cart
    if @cart.line_items.empty?
      redirect_to cart_url(current_user.cart.id), alert: "Your cart is empty!"
      return
    end
    
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @cart = current_user.cart
    @order = Order.new(order_params)
    @order.user = current_user
    @order.add_line_items_from_cart(@cart)
    respond_to do |format|
      if @order.save
        @cart.line_items.update_all(cart_id: nil)
        format.html { redirect_to @order, notice: 'Thank you for your Order!.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:first_name, :last_name, :cc_type, :cc_number, :exp_month, :exp_year, :addr_1, :addr_2, :city, :zip, :state, :user_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for([@user, @order], :html => { :multipart => true, :class => "form-signup" }) do |f| %>
  <% us_states = [
      ['State', nil],
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
    months = [
      ['Exp Month', nil],
      ['January', '01'],
      ['February', '02'],
      ['March', '03'],
      ['April', '04'],
      ['May', '05'],
      ['June', '06'],
      ['July', '07'],
    ['August', '08'],
      ['September', '09'],
      ['October', '10'],
      ['November', '11'],
      ['December', '12']
    ]
    years = [
      ['Exp Year', nil],
      ['2013', '2013'],
      ['2014', '2014'],
      ['2015', '2015'],
      ['2016', '2016'],
      ['2017', '2017'],
      ['2018', '2018'],
      ['2019', '2019'],
      ['2020', '2020'],
      ['2021', '2021']
    ]
    cc_types = [
      ['Payment Card Type', nil],
      ['American Express', 'Amex'],
      ['Mastercard', 'Mastercard'],
      ['Visa', 'Visa']
    ]
      %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
      The form contains <%= pluralize(@order.errors.count, "error") %>
      </div>
      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2>Billing Information</h3>
  <legend>CREDIT/DEBIT CARD INFORMATION</legend>
    <%= f.text_field :first_name, :value => current_user.fname %><br />
    <%= f.text_field :last_name, :value => current_user.lname %><br />
    <%= f.select :cc_type, options_for_select(cc_types) %><br />
    <%= f.text_field :cc_number, :placeholder => "Card Number" %><br />
    <%= f.text_field :cvv, :placeholder => "Security Code" %><br />
    <%= f.select :exp_month, options_for_select(months) %>
    <%= f.select :exp_year, options_for_select(years) %><br />
    <legend>BILLING ADDRESS</legend>
    <%= f.text_field :addr_1, :placeholder => "Address 1" %><br />
    <%= f.text_field :addr_2, :placeholder => "Address 2" %><br />
    <%= f.text_field :city, :placeholder => "City" %><br />
    <%= f.text_field :zip, :placeholder => "Zip Code" %><br />
    <%= f.select :state, options_for_select(us_states) %><br />
  <div class="form-actions">
    <%= f.submit "Place Order", :class => "btn btn-success" %>
  </div>
<% end %>
                                                                                                    

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Cc type</th>
      <th>Cc number</th>
      <th>Exp month</th>
      <th>Exp year</th>
      <th>Addr 1</th>
      <th>Addr 2</th>
      <th>City</th>
      <th>Zip</th>
      <th>State</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.first_name %></td>
        <td><%= order.last_name %></td>
        <td><%= order.cc_type %></td>
        <td><%= order.cc_number %></td>
        <td><%= order.exp_month %></td>
        <td><%= order.exp_year %></td>
        <td><%= order.addr_1 %></td>
        <td><%= order.addr_2 %></td>
        <td><%= order.city %></td>
        <td><%= order.zip %></td>
        <td><%= order.state %></td>
        <td><%= order.user %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/show.html.erb
<h2> Shopping Cart</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>TRACK NAME</th>
      <th>ARTISTS</th>
      <th>GENRE</th>
      <th>LENGTH</th>
      <th>BPM</th>
      <th>KEY</th>
      <th>RELEASE DATE</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% i=0
       total =0 %>
    <%  @order.line_items.each do |item|
      i+=1
      total += item.track.price %>
    <tr>
      <td><%= i %>.</td>
      <td><%= link_to item.track.title, track_path(item.track) %></td>
      <td>
        <% item.track.artists.each do |artist| %>
        <%= link_to artist.name, artist_path(artist) %>
        <%= ", " unless artist == item.track.artists.last %>
        <% end %>
      </td>
      <td><%= item.track.genre %></td>
      <td><%= item.track.length %></td>
      <td><%= item.track.bpm %></td>
      <td><%= item.track.key %></td>
      <td><%= item.track.release_date %></td>
      <td>$<%= item.track.price %></td>
      <td><%= link_to raw("<i class=\"icon-download-alt\"></i>"), item.track.audio_url,  class: "btn btn-danger btn-mini" %></td>
    </tr>
    <% end %>
  </tbody>
</table>