config/routes.rb
RhythmRefuge::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  get "home/index"
  get "query", to: "home#query"
  get "genres", to: "home#list_by_genre"

  devise_for :users
  resources :remixers

  resources :artists

  resources :tracks

  resources :users

  root 'home#index'

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  belongs_to :user

  def total_price
    line_items.to_a.sum { |item| item.price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = current_user.cart
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.line_items.delete_all    
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Your Cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<h2> Shopping Cart</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>TRACK NAME</th>
      <th>ARTISTS</th>
      <th>GENRE</th>
      <th>LENGTH</th>
      <th>BPM</th>
      <th>KEY</th>
      <th>RELEASE DATE</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% i=0
       total =0 %>
    <%  @cart.line_items.each do |item| 
      i+=1
      total += item.track.price %>
    <tr>
      <td><%= i %>.</td>
      <td><%= link_to item.track.title, track_path(item.track) %></td>
      <td>
        <% item.track.artists.each do |artist| %>
        <%= link_to artist.name, artist_path(artist) %>
        <%= ", " unless artist == item.track.artists.last %>
        <% end %>
      </td>
      <td><%= item.track.genre %></td>
      <td><%= item.track.length %></td>
      <td><%= item.track.bpm %></td>
      <td><%= item.track.key %></td>
      <td><%= item.track.release_date %></td>
      <td>$<%= item.track.price %></td>
      <td><%= link_to raw("<i class=\"icon-trash\"></i>"), item, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-mini" %></td>
    </tr>
    <% end %>
    <tr class="total_line info">
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>Total</td>
      <td class="total_cell">$<%= total %></td>
    </tr>
  </tbody>
</table>
<div>
  <%= button_to 'Empty Cart', @cart, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-mini" %>
  <%= button_to 'Checkout', new_order_path, method: :get, class: "btn btn-success btn-large" %>
</div>