config/routes.rb
RhythmRefuge::Application.routes.draw do
  resources :orders

  resources :line_items

  resources :carts

  get "home/index"
  get "query", to: "home#query"
  get "genres", to: "home#list_by_genre"

  devise_for :users
  resources :remixers

  resources :artists

  resources :tracks

  resources :users

  root 'home#index'

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  mount_uploader :picture, ImageUploader
  has_and_belongs_to_many :tracks

  validates :name, presence: true
  def self.query name
    if name
      find(:all, :conditions => ['name LIKE ?', "%#{name}%"])
    else
      find(:all)
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  belongs_to :user

  def total_price
    line_items.to_a.sum { |item| item.price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :track
  belongs_to :cart
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items

  validates :first_name, :last_name, :cc_type, :cc_number, :exp_month, :exp_year, :addr_1, :city, :zip, :state, :presence => true
  

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      self.line_items << item
    end
  end
end

app/models/remixer.rb
class Remixer < ActiveRecord::Base
  has_and_belongs_to_many :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
  mount_uploader :audio, AudioUploader
  
  has_and_belongs_to_many :artists
  has_and_belongs_to_many :remixers
  has_many :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :genre, :length, :bpm, :key,
            :release_date, :price, presence: true

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
  
  def self.query trkTitle
    puts "**********INSIDE MODEL TRACK******* #{trkTitle}"
    if trkTitle
      find(:all, :conditions => ['title LIKE ?', "%#{trkTitle}%"])
    else
      find(:all)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :cart, :dependent => :destroy
  has_many :orders

  validates :fname, :lname, presence: true
  before_save {self.fname = fname.capitalize}
  before_save {self.lname = lname.capitalize}
  after_create :create_cart
  after_create :make_first_user_admin

  def create_cart
    cart = Cart.new
    cart.user_id = self.id
    cart.save
  end

  def make_first_user_admin
    if self.id == 1
      self.update_attribute(:admin, true)
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @artists = Artist.find(:all).sample(5)
    @djs = Artist.find(:all).sample(3)
    @tracks = Track.find(:all).sample(10)
  end
  
  # Search Track or Artist from search Bar 
  def query
    @tracks = Track.query(params[:query])
    @artists = Artist.query(params[:query])
    
    if !(@tracks.empty? && @artists.empty?)
      flash[:notice] = "Showing search results for \"#{params[:query]}\""
    else
      flash[:alert] = "No results were found for \"#{params[:query]}\""
    end
  end

  def list_by_genre
    @tracks = Track.where(genre: params[:genre])
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/remixers_helper.rb
module RemixersHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.fname %></td>
        <td><%= admin.lname %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @admin.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @admin.lname %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RhythmRefuge</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">RhythmRefuge</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Home", root_path %></li>
            <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">Genres<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <% genres.each do |item| %>
                  <li><%= link_to item.genre, genres_path(:genre => item.genre) %></li>
                  <% end %>
                </ul>
            </li>
          </ul>
          <%= form_tag "/query", method: "get", class: "navbar-search navbar-left" do %>
            <div class="form-group">
              <div class="input-append">
                <%= text_field_tag :query, params[:query], :class => "form-control", :placeholder => "Search by Track or Artist" %>
                <%= button_tag :type => "submit", :class => "btn btn-default" do %>
                  <i class="icon-search"></i>
                <% end %>
              </div>
            </div>
          <% end %>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
            <li class="navbar-text">Welcome, <strong><%= current_user.fname %></strong></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <% if current_user.admin? %>
            <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">Admin Menu<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Add New Track', new_track_path %></li>
                  <li><%= link_to 'Add New Artist', new_artist_path %></li>
                </ul>
            </li>
            <% end %>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <li><%= link_to raw("<i class=\"icon-shopping-cart icon-white\"></i>"), cart_path(current_user.cart.id) %>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
          </ul>

        </div>
      </div>
    </div>
  </div>
  <div class="container main">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg %>
      </div>
    <% end %>
    
    <div class="container">
        <%= yield %>
    </div>
  </div>
  <div id="footer">
    <div class="container">
      <p class="muted credit">Copyright 2013 RhythmRefuge </p>
    </div>
  </div>

</body>
</html>